num_epochs = 1500
root_dir = '/home/rrathnak/Documents/Work/Task-2/Datasets/RoadCracks'
dataset = 'RoadCracks'
num_classes = 2
batch_size = 5
lr = 0.01
momentum = 0.9
optim_w_decay = 1e-5
step_size = 1500
gamma = 0.1
load_ckp = False
print_gpu_usage = False
dropout_prob = 0.05
mc_samples = 5
num_training = 35
repeats = 4
optimizer_name = 'SGD'
directory_name = str(dataset) + '_' + str(dropout_prob) + 'dropout_'+ str(num_training) + 'Train' + '_StepLR'
